#spring:
#  data:
#    mongodb:
#      host: mongodb://localhost
#      port: 27017
#      database: usermanagement
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/usermanagement